### ISSUE TITLE
Problems running HTMLTidy

### ISSUE THREAD

**Issue by bmix** [tylerl/FilterPipes#1]
Hi,
I am using Sublime3 on Windows7 and Python 2.7 as default Python. The external command I try to run identifies as: "HTML Tidy for Cygwin released on 1st September 2004". There is no newer version for Cygwin.

If no output filepath is given to Tidy, it returns the tidied document on STDOUT. However, it also may dump a lot of errors and warnings (even if an output file name has been set). This, however, can be switched off by setting an error file. Thus my configuration for this FilterPipe is:

``` JSON
{
    "caption": "FilterPipes: Tidy up (XHTML)",
    "command": "filter_pipes_process",
    "args": {
        "command": ["tidy", "-config", "C:\\Users\\bmix\\tidy-xhtmlize.cfg", "-f", "tidy-errs.txt"],
        "shell": false
    }
},
```

SublimeText 3's console reports:

```
Error 2 executing command [tidy -config C:\Users\bmix\tidy-xhtmlize.cfg -f tidy-errs.txt]:
b''
```

I can confirm, that FilterPipes passes the editor's text to Tidy (I saw parts of Tidy's error-report on the document when I left out the errs.txt re-routing). What I do not understand, however, is, that there is no result back, the text within the editor stays the same, rather than being replaced with Tidy's output. I also do not understand the letter "b" with the two single-quote characters.

**Comment by tylerl** [comment]
Looks like your problem is that htmltidy returns an error status when there are warnings, which FilterPipes interprets as meaning that the output shouldn't be replaced. I'll put in a patch that allows you to say which return codes are expected.

**Comment by tylerl** [comment]
I'll have a new version up on package control in a while. In the mean time, you can try the latest version in github. (i.e. check out the github version and put it on your `Packages` directory; remove the .sublime-package file from your `Installed Packages` dir).

You can now specify your expected return codes like this:

``` json
    {
        "caption": "HTML Tidy",
        "command": "filter_pipes_process",
        "args": {
            "command": ["tidy","-config","/Users/tylerl/htmltidy.conf"],
            "shell": false,
            "expected_returns": [0,1]
        }
    }
```

The [exit status values for htmltidy](http://tidy.sourceforge.net/docs/tidy_man.html#EXIT STATUS) are 0, 1, and 2; where 0 means no issues, 1 means warnings in the file, and 2 means errors in the file. My config above says to accept 0 and 1, but don't accept 2. Though you can set your configuration however you like.

Note that I'm not sending the warnings to a file like you did -- the reason is that warnings should be sent out on stderr not stdout, so they won't interfere with your output. My own testing bears that out on OSX; I assume the version on Windows works the same.

**Comment by bmix** [comment]
It's a runner, thanks a lot!

I did re-route the output, since, on Windows, with the different line-endings, the output in the console was not of much help and I wanted to see, what's going on.
