### ISSUE TITLE
Parsing file from stdin?

### ISSUE THREAD

**Issue by bmix** [tylerl/FilterPipes#5]
I try formatting via [`xmllint --format`](http://xmlsoft.org/xmllint.html) but to no avail. `xmllint` accepts input either via filename (last position on command-line) or via `stdin`. Then the typical `"-"` must be added. I tried with and without `"-"`. I also tried setting `shell` to `true` and put all into a single string (`"xmllint --format"` with and without `"-"`) but that tries to parse the whole string as the command's path/name, which, of course, breaks.
If I leave out the `"-"`, then I get the usage message of the `xmllint` command in return (but nothing else). If I add the `"-"` then nothing happens and `FitlerPipes` signals: Nothing changed. So, currently I have this:

```json
{
  "caption": "FilterPipes: Format XML (xmllint)",
  "command": "filter_pipes_process",
  "args": { "command": ["xmllint", "--format", "-"] }
}
```
but that does not work out as I would have expected. As a sidenote: I am on Win10 with Cygwin installed (that's the verision of `xmllint` I use). Thanks.

**Comment by tylerl** [comment]
I copy-pasted your configuration exactly into my `.sublime-commands` file on my OSX machine, and it worked perfectly. So I think you have the right idea, but I think that something about your environment is getting in the way.

Try bringing up the console window in sublime (typically <kbd>CTRL</kbd><kbd>`</kbd>) to see the error it produces if it fails.

If FilterPipes says "No change", then that means that the command succeeded, and the output it produced is exactly equal to the input you sent to it, such as you'd get by sending the content through `/bin/cat`. Otherwise, if the command returns a non-zero status code (e.g. like you get with `/bin/false`), then the message will say that the command failed. And if the command returns a zero status code but doesn't output any content (e.g. `/bin/true`), then your selection will be replaced with no content (e.g. it'll be deleted).

One other thing to try to make sure that selections aren't getting in the way is to set `"use_selections": false` in your args, which will send the whole file through your command even if you have part of the file selected.

Finally, I'd suggest making sure that you're not sending xmllint a properly-formatted doc to start with. Otherwise you'd *expect* there to be no change, which is what it sounds like is happening.

**Comment by bmix** [comment]
Hmmm...today I just tested it again and it worked. So I close this as one of those "close encounters with the paranormal" non-issues. Thank you for investigating. I still don't understand what happened. All I did was to put the machine into standby for a few hours...

**Comment by bmix** [comment]
Ah, just had to come back at it, can't keep it to myself any longer: I just wanted to express my gratitude for this super-nifty little package :^) Thanks a lot!
